[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=self, microphone=self, geolocation=self, payment=()"
    Content-Security-Policy = "default-src 'self'; 
      script-src 'self' 'unsafe-inline'; 
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; 
      font-src https://fonts.gstatic.com https://fonts.googleapis.com; 
      img-src 'self' data: https: cloudinary.com; 
      connect-src 'self' https://pawbook-production.up.railway.app"

[[headers]]
  for = "/gcu"  # Configuration spécifique à la page CGU
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"